console.log(10+"20");
console.log(10-"5");
console.log("java"+"script");
console.log(" "+" ");
console.log(" " + 0);
console.log("ashok"-"ok");
console.log(true+true);
console.log(true+false);
console.log(false+false);
console.log(false-true);